# 重回帰モデル

In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import math
import numpy as np
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns


# データ読み込み
cal_housing = pd.read_csv('datasets/cal_housing/CaliforniaHousing/cal_housing.data', sep=',')
cal_housing.columns = ['longitude', 'latitude', 'housingMedianAge', 'totalRooms', 'totalBedrooms', 'population', 'households', 'medianIncome', 'medianHouseValue']


# データクレンジング
def cleansing(df, col, n):
  mean = df[col].mean()
  std = df[col].std()

  df = df[(df[col] > mean - n * std) & (df[col] < mean + n * std)]
  
  return df

cal_housing = cleansing(cal_housing, 'housingMedianAge', 2)
cal_housing = cleansing(cal_housing, 'totalRooms', 2)
cal_housing = cleansing(cal_housing, 'totalBedrooms', 2)
cal_housing = cleansing(cal_housing, 'population', 2)
cal_housing = cleansing(cal_housing, 'households', 2)
cal_housing = cleansing(cal_housing, 'medianIncome', 2)
cal_housing = cleansing(cal_housing, 'medianHouseValue', 2)


# 関連する基本統計量
display(cal_housing.describe())

def train(X, y):
  # 訓練データとテストデータに分割
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

  # 学習
  model = LinearRegression()
  model.fit(X_train, y_train)

  # 評価
  mse = mean_squared_error(y_test, model.predict(X_test))
  r2 = r2_score(y_test, model.predict(X_test))
  print('COEF', model.coef_)
  print('INTERCEPT', model.intercept_)
  print('MSE:', mse)
  print('R2:', r2)

  return model


# 学習・評価
X = cal_housing[['longitude', 'latitude', 'housingMedianAge', 'totalRooms', 'totalBedrooms', 'population', 'households', 'medianIncome']]
longitude_model = train(X, cal_housing['medianHouseValue'])

,longitude,latitude,housingMedianAge,totalRooms,totalBedrooms,population,households,medianIncome,medianHouseValue
count,15648.000000,15648.000000,15648.000000,15648.000000,15648.000000,15648.000000,15648.000000,15648.000000,15648.000000
mean,-119.611961,35.729048,29.915836,2000.000383,410.934369,1116.581097,384.378195,3.527576,178709.624041
std,2.004892,2.184998,12.069361,949.868324,181.436156,507.466004,167.153233,1.404762,84774.564866
min,-124.350000,32.540000,4.000000,26.000000,14.000000,27.000000,20.000000,0.499900,14999.000000
25%,-121.760000,33.940000,20.000000,1324.750000,279.000000,748.750000,264.000000,2.455400,110400.000000
50%,-118.770000,34.420000,31.000000,1878.000000,393.000000,1065.000000,370.000000,3.358150,165300.000000
75%,-118.030000,37.750000,38.000000,2584.000000,533.000000,1454.000000,499.000000,4.430750,233725.000000
max,-114.490000,41.950000,52.000000,6349.000000,1047.000000,2519.000000,779.000000,7.723400,405400.000000

COEF [-3.41981934e+04 -3.40961332e+04  6.86904905e+02 -1.89341475e+01
  1.67598822e+02 -5.71386826e+01  1.10698213e+02  3.91439365e+04]
INTERCEPT -2862317.153045594
MSE: 2742822915.537325
R2: 0.6257296688234251